In [7]:
import numpy as np
import pandas as pd
from sklearn import set_config
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
import category_encoders as ce
from sklearn.compose import make_column_selector

In [8]:
path =  r'C:\Users\RaNia PC\Desktop\Axsos\sales_predictions_2023.csv.xlsx'
df = pd.read_excel(path)
df.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052

In [9]:
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(0)

In [10]:
# Fix inconsistent categorical data
df["Item_Fat_Content"] = df["Item_Fat_Content"].replace(
    {"LF": "Low Fat", "low fat": "Low Fat", "reg": "Regular"})

features and target

In [11]:
X = df.drop(columns=["Item_Outlet_Sales", "Item_Identifier"])
y = df["Item_Outlet_Sales"]
X.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2
2,17.50,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1
3,19.20,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store
4,8.93,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1

. Train-Test Split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42)

preprocessing pipeline

In [13]:
from sklearn.pipeline import make_pipeline

# column names
num_cols = X_train.select_dtypes(include=[np.number]).columns.tolist()
num_cols

['Item_Weight', 'Item_Visibility', 'Item_MRP', 'Outlet_Establishment_Year']

In [14]:
cat_cols = make_column_selector(dtype_include = 'object')
cat_cols(X_train)

['Item_Fat_Content',
 'Item_Type',
 'Outlet_Identifier',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type']

In [15]:
# preprocessing for numeric features(Impute then Scale) and  categorical features (Impute then Encode)
num_processor = make_pipeline(SimpleImputer(strategy="mean"), StandardScaler())
cat_processor = make_pipeline(SimpleImputer(strategy="most_frequent"),
    OneHotEncoder(handle_unknown="ignore", sparse_output=False),)

In [16]:
preprocessor = ColumnTransformer(
    transformers=[
        ("num", num_processor, num_cols),
        ("cat", cat_processor, cat_cols),
    ],
    remainder="drop",)

In [17]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

In [18]:
X_train.head()

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
1921,7.72,Regular,0.147904,Fruits and Vegetables,116.6466,OUT010,1998,NaN,Tier 3,Grocery Store
655,19.75,Low Fat,0.014301,Household,103.0332,OUT046,1997,Small,Tier 1,Supermarket Type1
2229,NaN,Regular,0.054221,Breads,129.1310,OUT027,1985,Medium,Tier 3,Supermarket Type3
2537,19.35,Low Fat,0.118342,Snack Foods,222.6088,OUT045,2002,NaN,Tier 2,Supermarket Type1
3528,18.35,Regular,0.092150,Frozen Foods,184.8266,OUT013,1987,High,Tier 3,Supermarket Type1

In [19]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 5966 entries, 1921 to 7270
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Weight                4943 non-null   float64
 1   Item_Fat_Content           5966 non-null   str
 2   Item_Visibility            5966 non-null   float64
 3   Item_Type                  5966 non-null   str
 4   Item_MRP                   5966 non-null   float64
 5   Outlet_Identifier          5966 non-null   str
 6   Outlet_Establishment_Year  5966 non-null   int64
 7   Outlet_Size                4276 non-null   str
 8   Outlet_Location_Type       5966 non-null   str
 9   Outlet_Type                5966 non-null   str
dtypes: float64(3), int64(1), str(6)
memory usage: 512.7 KB

In [20]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

In [21]:
lr_model = LinearRegression()

In [22]:
#lr_model.fit(X_train, y_train)
lr_model.fit(X_train_processed, y_train)

LinearRegression()

In [23]:
# evaluate
from sklearn.metrics import r2_score

def evaluate_model(model, X_train, y_train, X_test, y_test):
    # 1. Get predictions
    train_preds = model.predict(X_train)
    test_preds = model.predict(X_test)

    train_r2 = r2_score(y_train, train_preds)
    test_r2 = r2_score(y_test, test_preds)

    print(f" {model} Evaluation")
    print(f"Training R²: {train_r2}")
    print(f"Testing R² :  {test_r2}")

In [24]:
# Evaluate Linear Regression
evaluate_model(lr_model, X_train_processed, y_train, X_test_processed, y_test)

 LinearRegression() Evaluation
Training R²: 0.5608785966604157
Testing R² :  0.5678856047927665

In [25]:
# Random Forest
rf_model = RandomForestRegressor(random_state=42)

In [26]:
rf_model.fit(X_train_processed, y_train)

RandomForestRegressor(random_state=42)

In [27]:
evaluate_model(rf_model, X_train_processed, y_train, X_test_processed, y_test)

 RandomForestRegressor(random_state=42) Evaluation
Training R²: 0.9383150770677271
Testing R² :  0.552963479291234

1. Linear Regression AnalysisTraining $R^2$: 0.5609Testing $R^2$: 0.5679 ( underfitting)

2. Random Forest AnalysisTraining $R^2$: 0.9383Testing $R^2$: 0.5530(overfitting)

Linear Regression is better it achieves the better test score.

limiting max_depth to prevent the model from overfitting( tuning)

In [28]:
rf_tuned = RandomForestRegressor(max_depth=5, random_state=42)
rf_tuned.fit(X_train_processed, y_train)

RandomForestRegressor(max_depth=5, random_state=42)

In [29]:
evaluate_model(rf_tuned, X_train_processed, y_train, X_test_processed, y_test)

 RandomForestRegressor(max_depth=5, random_state=42) Evaluation
Training R²: 0.6111149022221982
Testing R² :  0.6020985912795348

GridSearchCV

In [30]:
rf_base = RandomForestRegressor(random_state=42)

In [35]:
#  grid of hyperparameters to test
param_grid = {
    'max_depth': [3, 5, 8, 10],
    'min_samples_leaf': [2, 5, 10, 15]
}

In [36]:
#Grid Search with Cross-Validation
grid_search = GridSearchCV(estimator=rf_base, param_grid=param_grid, cv=5, scoring='r2', n_jobs=-1)

In [37]:
grid_search.fit(X_train_processed, y_train)

GridSearchCV(cv=5, estimator=RandomForestRegressor(random_state=42), n_jobs=-1,
             param_grid={'max_depth': [3, 5, 8, 10],
                         'min_samples_leaf': [2, 5, 10, 15]},
             scoring='r2')

In [38]:
print("Best Hyperparameters ")
print(grid_search.best_params_)

Best Hyperparameters
{'max_depth': 5, 'min_samples_leaf': 15}

In [39]:
best_rf_model = grid_search.best_estimator_

evaluate_model(best_rf_model, X_train_processed, y_train, X_test_processed, y_test)

 RandomForestRegressor(max_depth=5, min_samples_leaf=15, random_state=42) Evaluation
Training R²: 0.6093075404123505
Testing R² :  0.6017002039560324

This will be the best Model(GridSearchCV (`max_depth=5`, `min_samples_leaf=15`)

* ** (R-squared) score, which acts like an overall accuracy to understand the data ( from 0 - 100%)
* **Linear Regression** was too simple and underfit the complex data ($Testing\ R^2 = 0.5679$).
* **Default Random Forest** suffered from severe overfitting($Testing\ R^2 = 0.5530$).
* **GridSearchCV Tuned Random Forest** achieved our best overall generalizing performance with a **Testing $R^2$ of 0.6017**
* the last model successfully explains and understand  **60.17% of the new data

In [40]:
from sklearn.metrics import mean_absolute_error

In [57]:
# MAE
train_preds = best_rf_model.predict(X_train_processed)
test_preds = best_rf_model.predict(X_test_processed)

train_mae = mean_absolute_error(y_train, train_preds)
test_mae = mean_absolute_error(y_test, test_preds)
print(f"Random Forest MAE Evaluation")
print(f"Training MAE: {train_mae}")
print(f"Testing MAE:  {test_mae}")
print(f"mean_price test:  {y_test.mean()}")
print(f"mean_price train:  {y_train.mean()}")

Random Forest MAE Evaluation
Training MAE: 755.3289925871314
Testing MAE:  737.1295444289038
mean_price test:  2126.24024168948
mean_price train:  2204.8825196781763

In [52]:
mean_price = y_test.mean()
error_percentage = (737.1295 / mean_price) * 100

print(error_percentage)

34.66821319373992

* MAE is measures the average distance between  model's predictions and actual data , using the exact same unit.

*  when forecasting sales for any product, the model predictions will on average, deviate from actual retail sales by  737.13 units
* This allows the commercial team to budget risk